### ISSUE TITLE
Timings needed

### ISSUE THREAD

**Issue by chemphys** [paesanilab/mbpol_openmm_plugin#120]
Hey @zonca 
In order to decide what to use and from where, it would be great if we can have the following timings.
For a SINGLE POINT CALCULATION:
- 1b energy calculation
- 2b energy calculations (polynomials + dispersion, all together or sepaarate, does not matter)
- 3b energy calculation
- Permanent electrostatics
- Induce electrostatics

For 100 steps of an md simulation:
Average time for each one of the previously mentioned parts.

All these timings will be for a **cluster system**. Just assume a dummy name for the input and I will change it. Ideally, what I would need from you is the following:
- Create a new branch where you flag all these timings
- Put each calculation setup in a different folder
- Create a run script that I can just run and get the info, for both calculations.

I will run this on tscc up to 16 cores, so please make sure that you use the CPU platform.

Then, it would be great to have the same info for a periodic boundary conditions system, both single point and simulation. Also, here I would like to see the time that it takes the EWALD part. **I do not have an input for this, so if you can use one of yours and put it there, I will appreciate it.** I will do the same, run it on tscc up to 16 cores.

After the tests are done, we can delete the branch.

Please, let me know if is not clear. Thanks!

**Comment by agoetz** [comment]
It would be useful to keep timers in the code so that in the future we can easily check performance of individual contributions with different hard-/software stacks. Useful for code maintenance and presentations/publications.

**Comment by zonca** [comment]
I could not find a way to add a timer that aggregates across all the iterations of a simulation. However I think there is a workaround:

* in the integrator, set a tiny timestep, I tested for example 1e-6 femtoseconds, but we can do less if necessary, so that for 100 timesteps the molecules do not move much.
* create different versions of `mbpol.xml`, each has only 1 component, see https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/mbpol.xml , remember that `<Script>` is the dispersion force
* run simulations for each one, both single point and integrated.

About PME you can use this input PDB: https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/tests/pdb_files/water256_integration_test.pdb

For PME Electrostatics, the computation is done in 5 parts:

* `calculatePmeDirectElectrostaticPairIxn`
* `computeReciprocalSpaceInducedDipoleForceAndEnergy`
* `computeReciprocalSpaceFixedElectrostaticsForceAndEnergy`
* `calculatePmeSelfEnergy`
* Charge derivatives contribution to Forces (https://github.com/paesanilab/mbpol_openmm_plugin/blob/5a86c5a6fd6e7fd451151e03b0a3574111315906/platforms/reference/src/MBPolReferenceElectrostaticsForce.cpp#L2771)

In the CPU plaftorm, all of that is in a parallel section, fully threaded, it would be too complicated to implement timing there. So the other option would be to implement timing in the Reference platform which is single threaded. Do you think that would be useful?

**Comment by zonca** [comment]
It is the same scripts you ran before on Ockam. Just change the XML.

Do you want me to prepare the 4 XMLs?

**Comment by zonca** [comment]
https://gist.github.com/zonca/1243e0b6548dade2f7c4b63a6ca1175e
